### ISSUE TITLE
using members_current_user_has_role() instead of current_user_can() ?

### ISSUE THREAD

**Issue by acorbi** [opendata-swiss/wp-ckan-backend#4]
I have just installed the plugin on my WP multi-site instance, tweaked the wp-config.php file as described on README.md, activated it (both network-wide and  just for a single site) and headed to the WP Dashboard to check its functionalities. When I click on **Datasets > All datasets** I get following error message:

```
Fatal error: Call to undefined function members_current_user_has_role() in /var/www/html/wp-content/plugins/wp-ckan-backend/post-types/ckan-backend-local-dataset.php on line 259
```

Since the function **members_current_user_has_role** is not defined on your plugin's code, I guess this is a WP-specific funtion. However, a search on the wordpress codex does not retrieve any result for it: https://wordpress.org/search/members_current_user_has_role

Shouldn't the plugin use the function **current_user_can** (https://developer.wordpress.org/reference/functions/current_user_can/)?

**Comment by metaodi** [comment]
@acorbi I think `members_current_user_has_role` is a function we used from the [Members plugin](https://github.com/justintadlock/members), but you're right, we didn't mention this anywhere, it's it can be replaced by `current_user_can`

**Comment by acorbi** [comment]
hey @metaodi , hi!

Yeah, see https://github.com/opendata-swiss/wp-ckan-backend/pull/5. it works on my development environment

**Comment by tschortsch** [comment]
We shouldn't directly replace the `members_current_user_has_role` with the WordPress `current_user_can` function. The codex (https://developer.wordpress.org/reference/functions/current_user_can/) mentions the following when it comes to use this function to check against roles:
> While checking against particular roles in place of a capability is supported in part, this practice is discouraged as it may produce unreliable results.

I think we rather should document the dependency to the members plugin (https://wordpress.org/plugins-wp/members/). I will have a look if it makes sense to remove this dependency completely.

**Comment by tschortsch** [comment]
I removed the dependency in this pull request: https://github.com/opendata-swiss/wp-ckan-backend/pull/8
